name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build TeXLive and R
    runs-on: debian-latest
    env:
      TAG: ghcr.io/abnt-latex/texlive-r
      VERSION: 1.0.2
    steps:
      - name: Informações
        run: |
          echo "actor ${{ github.actor }}" /
          echo "${{ env.TAG }}:${{ env.VERSION }}"
      - name: Configurar o código do repositório
        uses: actions/checkout@v4
      - name: Configurar o Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          load: true
          tags: texlive-r
      - name: Login no Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Publicar container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}:${{ env.VERSION }},${{ env.TAG }}:latest
      