name: Build Docker Image

on:
  push:
    branches: [ main ]

env:
  TAG: ghcr.io/abnt-latex/texlive-r
  VERSION: 1.0.2

jobs:
  build:
    name: Build TeXLive and R
    runs-on: ubuntu-latest
    steps:
      - name: Informações
        run: |
          echo "actor ${{ github.actor }}" /
          echo "${{ env.TAG }}:${{ env.VERSION }}"
      - name: Configurar o código do repositório
        uses: actions/checkout@v4
      - name: Configurar o Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          load: true
          tags: texlive-r
      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Publicar container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}:${{ env.VERSION }},${{ env.TAG }}:latest
  test:
    name: Tests TeXLive and R
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Confira o código do repositório
        uses: actions/checkout@v4
      - name: Compilando os arquivos na Docker
        run: docker run --rm -v ${{ github.workspace }}/examples:/content --workdir /content --entrypoint ./build.sh ${{ env.TAG }}:${{ env.VERSION }}
      - name: Listar arquivos dentro do repositório
        run: |
          ls -a ${{ github.workspace }}/examples
      - name: Verficar arquivo pdf
        run: |
          file examples/main.pdf | grep -q ' PDF '
      - name: Carregar arquivos estáticos como artefato
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: examples/main.pdf
  deploy:
    name: Deploy no Github Pages
    needs: [build,test]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy no Github Pages
        id: deployment
        uses: actions/deploy-pages@v4